"""Consolidated initial schema.

Generated from the ORM metadata by scripts/generate-initial-migration.py.
Do not edit by hand: regenerate it, and add later changes as new migrations.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES: tuple[str, ...] = (
    "backoffice_command",
    "backoffice_second_password_version",
    "backoffice_secret_version",
    "core_data_source",
    "core_market",
    "exec_broker",
    "exec_order",
    "exec_order_intent",
    "exec_order_intent_legacy_strategy_link",
    "exec_reconciliation_diff",
    "ops_audit_log",
    "ops_inbox_dead_letter",
    "ops_inbox_event",
    "ops_incident",
    "ops_outbox_event",
    "ops_runtime_instance",
    "ops_scheduler_lease",
    "ops_trading_control",
    "risk_budget_anchor",
    "risk_decision",
    "risk_policy",
    "strategy_definition",
    "strategy_source_reference",
    "backoffice_bootstrap_authority",
    "backoffice_secret_activation",
    "core_exchange",
    "exec_account",
    "exec_broker_order_link",
    "exec_order_command_authority",
    "exec_order_event",
    "exec_order_status_watermark",
    "exec_paper_order",
    "risk_policy_version",
    "strategy_version",
    "core_instrument",
    "exec_account_risk_policy_binding",
    "exec_account_snapshot",
    "exec_broker_order_status_event",
    "exec_provider_account_binding",
    "exec_reconciliation_run",
    "risk_budget_reservation",
    "strategy_david_v6_manifest",
    "strategy_feature_schema",
    "strategy_rule",
    "strategy_setup",
    "binance_usdm_reconciliation_run",
    "exec_broker_execution_watermark",
    "exec_cash_snapshot",
    "exec_fill",
    "exec_order_command",
    "exec_position",
    "risk_snapshot",
    "strategy_feature_snapshot",
    "strategy_rule_source",
    "toss_us_reconciliation_run",
    "toss_us_recovery_lease",
    "binance_usdm_algo_order_fact",
    "binance_usdm_balance_fact",
    "binance_usdm_configuration_fact",
    "binance_usdm_income_fact",
    "binance_usdm_order_fact",
    "binance_usdm_position_fact",
    "binance_usdm_trade_fact",
    "exec_execution_checkpoint_scope",
    "exec_execution_gap",
    "exec_fill_charge_component",
    "exec_position_lifecycle",
    "exec_position_lot",
    "risk_david_v6_session_anchor",
    "strategy_signal",
    "toss_us_cash_fact",
    "toss_us_order_fact",
    "toss_us_position_fact",
    "strategy_david_v6_decision",
    "strategy_david_v6_blocker",
    "strategy_david_v6_indicator",
)

_CREATE: tuple[str, ...] = (
    """CREATE TABLE backoffice_command (
    id BINARY(16) NOT NULL,
    actor_email VARCHAR(254) COLLATE ascii_bin NOT NULL,
    source_ip VARCHAR(45) COLLATE ascii_bin NOT NULL,
    action VARCHAR(64) COLLATE ascii_bin NOT NULL,
    target_type VARCHAR(64) COLLATE ascii_bin NOT NULL,
    target_key VARCHAR(512) COLLATE utf8mb4_bin NOT NULL,
    payload_digest BINARY(32) NOT NULL,
    expected_digest BINARY(32),
    status VARCHAR(16) COLLATE ascii_bin NOT NULL,
    result_code VARCHAR(128) COLLATE ascii_bin,
    result_digest BINARY(32),
    started_at DATETIME NOT NULL,
    completed_at DATETIME,
    PRIMARY KEY (id),
    CONSTRAINT ck_backoffice_command_scope CHECK (actor_email = 'lmhml0237@gmail.com' AND CHAR_LENGTH(actor_email) > 0 AND actor_email = TRIM(actor_email) AND CHAR_LENGTH(source_ip) > 0 AND source_ip = TRIM(source_ip) AND CHAR_LENGTH(action) > 0 AND action = TRIM(action) AND CHAR_LENGTH(target_type) > 0 AND target_type = TRIM(target_type) AND CHAR_LENGTH(target_key) > 0 AND target_key = TRIM(target_key) AND CHAR_LENGTH(status) > 0 AND status = TRIM(status)),
    CONSTRAINT ck_backoffice_command_digests CHECK (OCTET_LENGTH(payload_digest) = 32 AND (expected_digest IS NULL OR OCTET_LENGTH(expected_digest) = 32)),
    CONSTRAINT ck_backoffice_command_state CHECK ((status = 'IN_PROGRESS' AND result_code IS NULL AND result_digest IS NULL AND completed_at IS NULL) OR (status IN ('SUCCEEDED', 'FAILED') AND CHAR_LENGTH(result_code) > 0 AND result_code = TRIM(result_code) AND OCTET_LENGTH(result_digest) = 32 AND completed_at >= started_at))
)""",
    """CREATE TABLE backoffice_second_password_version (
    id BINARY(16) NOT NULL,
    version BIGINT NOT NULL,
    verifier VARCHAR(512) COLLATE utf8mb4_bin NOT NULL,
    created_at DATETIME NOT NULL,
    retired_at DATETIME,
    active_marker VARCHAR(6) COLLATE ascii_bin,
    PRIMARY KEY (id),
    CONSTRAINT uq_backoffice_second_password_version UNIQUE (version),
    CONSTRAINT uq_backoffice_second_password_active UNIQUE (active_marker),
    CONSTRAINT ck_backoffice_second_password_verifier CHECK (version > 0 AND verifier LIKE '$argon2id$%%' AND CHAR_LENGTH(verifier) > 0 AND verifier = TRIM(verifier)),
    CONSTRAINT ck_backoffice_second_password_state CHECK ((retired_at IS NULL AND active_marker = 'ACTIVE') OR (retired_at > created_at AND active_marker IS NULL))
)""",
    """CREATE TABLE backoffice_secret_version (
    id BINARY(16) NOT NULL,
    logical_name VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    category VARCHAR(32) COLLATE ascii_bin NOT NULL,
    provider_code VARCHAR(16) COLLATE ascii_bin,
    environment VARCHAR(16) COLLATE ascii_bin,
    version BIGINT NOT NULL,
    ciphertext VARBINARY(8192) NOT NULL,
    nonce BINARY(12) NOT NULL,
    aad_schema_version BIGINT NOT NULL,
    master_key_version BIGINT NOT NULL,
    fingerprint BINARY(32) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_backoffice_secret_version_name_version UNIQUE (logical_name, version),
    CONSTRAINT uq_backoffice_secret_version_exact_scope UNIQUE (id, logical_name),
    CONSTRAINT ck_backoffice_secret_version_category CHECK (category IN ('PROVIDER_CREDENTIAL', 'ACCOUNT_IDENTIFIER', 'OAUTH')),
    CONSTRAINT ck_backoffice_secret_version_scope CHECK ((category = 'OAUTH' AND provider_code = 'GOOGLE' AND environment IS NULL) OR (category IN ('PROVIDER_CREDENTIAL', 'ACCOUNT_IDENTIFIER') AND provider_code IN ('KIS', 'TOSS', 'BINANCE') AND environment IN ('PAPER', 'LIVE'))),
    CONSTRAINT ck_backoffice_secret_version_crypto CHECK (OCTET_LENGTH(ciphertext) > 0 AND OCTET_LENGTH(ciphertext) <= 8192 AND OCTET_LENGTH(nonce) = 12 AND OCTET_LENGTH(fingerprint) = 32 AND version > 0 AND aad_schema_version = 1 AND master_key_version > 0)
)""",
    """CREATE TABLE core_data_source (
    id BINARY(16) NOT NULL,
    code VARCHAR(32) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_core_data_source_code UNIQUE (code),
    CONSTRAINT ck_core_data_source_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
)""",
    """CREATE TABLE core_market (
    id BINARY(16) NOT NULL,
    code VARCHAR(16) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_core_market_code UNIQUE (code),
    CONSTRAINT ck_core_market_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
)""",
    """CREATE TABLE exec_broker (
    id BINARY(16) NOT NULL,
    code VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_exec_broker_code UNIQUE (code),
    CONSTRAINT uq_exec_broker_id_code UNIQUE (id, code)
)""",
    """CREATE TABLE exec_order (
    id BINARY(16) NOT NULL,
    order_intent_id BINARY(16) NOT NULL,
    risk_decision_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    broker_client_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_style VARCHAR(16) NOT NULL,
    requested_quantity NUMERIC(38, 18) NOT NULL,
    filled_quantity NUMERIC(38, 18) NOT NULL,
    limit_price NUMERIC(38, 18),
    status VARCHAR(24) NOT NULL,
    aggregate_version BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_order_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_decision_intent FOREIGN KEY(risk_decision_id, order_intent_id) REFERENCES risk_decision (id, order_intent_id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_intent FOREIGN KEY(order_intent_id) REFERENCES exec_order_intent (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_order_aggregate_version CHECK (aggregate_version >= 0),
    CONSTRAINT ck_exec_order_quantities CHECK ((requested_quantity > 0) and (filled_quantity >= 0)),
    CONSTRAINT uq_exec_order_intent UNIQUE (order_intent_id),
    CONSTRAINT uq_exec_order_account_client_id UNIQUE (account_id, broker_client_order_id)
)""",
    """CREATE TABLE exec_order_intent (
    id BINARY(16) NOT NULL,
    origin_type VARCHAR(16) NOT NULL,
    idempotency_key VARCHAR(256) COLLATE ascii_bin NOT NULL,
    canonical_payload_hash BINARY(32) NOT NULL,
    account_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    intent_type VARCHAR(16) NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_style VARCHAR(16) NOT NULL,
    requested_quantity NUMERIC(38, 18) NOT NULL,
    limit_price NUMERIC(38, 18),
    strategy_signal_id BINARY(16),
    legacy_strategy_link_id BINARY(16),
    protection_position_id BINARY(16),
    protection_reason_code VARCHAR(128),
    operator_audit_id BINARY(16),
    reconciliation_diff_id BINARY(16),
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_order_intent_account FOREIGN KEY(account_id) REFERENCES exec_account (id),
    CONSTRAINT fk_exec_order_intent_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id),
    CONSTRAINT fk_exec_order_intent_operator_audit FOREIGN KEY(operator_audit_id) REFERENCES ops_audit_log (id),
    CONSTRAINT fk_exec_order_intent_protection_position FOREIGN KEY(protection_position_id) REFERENCES exec_position (id),
    CONSTRAINT fk_exec_order_intent_reconciliation_diff FOREIGN KEY(reconciliation_diff_id) REFERENCES exec_reconciliation_diff (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_intent_strategy_signal FOREIGN KEY(strategy_signal_id) REFERENCES strategy_signal (id),
    CONSTRAINT ck_exec_order_intent_origin CHECK (origin_type in ('STRATEGY','PROTECTION','OPERATOR','RECONCILIATION')),
    CONSTRAINT ck_exec_order_intent_terms CHECK ((requested_quantity > 0) and ((order_style <> 'LIMIT') or (limit_price > 0))),
    CONSTRAINT uq_exec_order_intent_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_exec_order_intent_legacy_strategy_link FOREIGN KEY(legacy_strategy_link_id) REFERENCES exec_order_intent_legacy_strategy_link (intent_id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_order_intent_origin_evidence CHECK ((origin_type = 'STRATEGY' AND ((strategy_signal_id IS NOT NULL AND legacy_strategy_link_id IS NULL) OR (strategy_signal_id IS NULL AND legacy_strategy_link_id IS NOT NULL AND legacy_strategy_link_id = id)) AND protection_position_id IS NULL AND operator_audit_id IS NULL AND reconciliation_diff_id IS NULL) OR (origin_type = 'PROTECTION' AND strategy_signal_id IS NULL AND legacy_strategy_link_id IS NULL AND protection_position_id IS NOT NULL AND protection_reason_code IS NOT NULL AND operator_audit_id IS NULL AND reconciliation_diff_id IS NULL) OR (origin_type = 'OPERATOR' AND strategy_signal_id IS NULL AND legacy_strategy_link_id IS NULL AND protection_position_id IS NULL AND operator_audit_id IS NOT NULL AND reconciliation_diff_id IS NULL) OR (origin_type = 'RECONCILIATION' AND strategy_signal_id IS NULL AND legacy_strategy_link_id IS NULL AND protection_position_id IS NULL AND operator_audit_id IS NULL AND reconciliation_diff_id IS NOT NULL))
)""",
    """CREATE TABLE exec_order_intent_legacy_strategy_link (
    intent_id BINARY(16) NOT NULL,
    PRIMARY KEY (intent_id),
    CONSTRAINT fk_exec_order_intent_legacy_link_intent FOREIGN KEY(intent_id) REFERENCES exec_order_intent (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE exec_reconciliation_diff (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    internal_order_id BINARY(16),
    broker_order_id VARCHAR(128) COLLATE ascii_bin,
    broker_execution_id VARCHAR(128) COLLATE ascii_bin,
    diff_key VARCHAR(256) COLLATE ascii_bin NOT NULL,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    expected_hash BINARY(32) NOT NULL,
    observed_hash BINARY(32) NOT NULL,
    created_at DATETIME NOT NULL,
    resolved_at DATETIME,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_reconciliation_diff_internal_order FOREIGN KEY(internal_order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_reconciliation_diff_run FOREIGN KEY(run_id) REFERENCES exec_reconciliation_run (id),
    CONSTRAINT ck_exec_reconciliation_diff_severity CHECK (severity in ('INFO','WARNING','BLOCKING')),
    CONSTRAINT ck_exec_reconciliation_diff_status CHECK (status in ('OPEN','RESOLVED')),
    CONSTRAINT uq_exec_reconciliation_diff_identity UNIQUE (run_id, diff_key)
)""",
    """CREATE TABLE ops_audit_log (
    id BINARY(16) NOT NULL,
    action VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    actor_runtime_instance_id BINARY(16),
    fencing_token INTEGER NOT NULL,
    details JSON NOT NULL,
    occurred_at DATETIME NOT NULL,
    PRIMARY KEY (id)
)""",
    """CREATE TABLE ops_inbox_dead_letter (
    id BINARY(16) NOT NULL,
    consumer_name VARCHAR(128) NOT NULL,
    event_id BINARY(16) NOT NULL,
    payload_hash BINARY(32) NOT NULL,
    reason_code VARCHAR(128) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_ops_inbox_dead_letter_identity UNIQUE (consumer_name, event_id, payload_hash)
)""",
    """CREATE TABLE ops_inbox_event (
    consumer_name VARCHAR(128) NOT NULL,
    event_id BINARY(16) NOT NULL,
    producer VARCHAR(128) NOT NULL,
    aggregate_type VARCHAR(128) NOT NULL,
    aggregate_id BINARY(16) NOT NULL,
    aggregate_version BIGINT NOT NULL,
    payload_hash BINARY(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    error VARCHAR(1024),
    next_attempt_at DATETIME,
    deadline_at DATETIME,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (consumer_name, event_id),
    CONSTRAINT ck_ops_inbox_status CHECK (status IN ('PROCESSED', 'WAITING_FOR_GAP'))
)""",
    """CREATE TABLE ops_incident (
    id BINARY(16) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    reason_code VARCHAR(128) NOT NULL,
    scope_type VARCHAR(32),
    scope_key VARCHAR(128),
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_ops_incident_severity CHECK (severity IN ('INFO', 'WARNING', 'BLOCKING')),
    CONSTRAINT ck_ops_incident_status CHECK (status IN ('OPEN', 'RESOLVED'))
)""",
    """CREATE TABLE ops_outbox_event (
    id BINARY(16) NOT NULL,
    event_id BINARY(16) NOT NULL,
    producer VARCHAR(128) NOT NULL,
    aggregate_type VARCHAR(128) NOT NULL,
    aggregate_id BINARY(16) NOT NULL,
    aggregate_version BIGINT NOT NULL,
    payload JSON NOT NULL,
    payload_hash BINARY(32) NOT NULL,
    next_attempt_at DATETIME NOT NULL,
    claimed_by VARCHAR(128),
    claim_expires_at DATETIME,
    published_at DATETIME,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_ops_outbox_event_id UNIQUE (event_id),
    CONSTRAINT uq_ops_outbox_aggregate_version UNIQUE (producer, aggregate_type, aggregate_id, aggregate_version)
)""",
    """CREATE TABLE ops_runtime_instance (
    id BINARY(16) NOT NULL,
    local_state VARCHAR(16) NOT NULL,
    started_at DATETIME NOT NULL,
    stopped_at DATETIME,
    PRIMARY KEY (id),
    CONSTRAINT ck_ops_runtime_instance_state CHECK (local_state in ('DISARMED','STANDBY'))
)""",
    """CREATE TABLE ops_scheduler_lease (
    lease_name VARCHAR(64) NOT NULL,
    owner_runtime_instance_id BINARY(16),
    acquired_at DATETIME,
    expires_at DATETIME,
    fencing_token INTEGER NOT NULL,
    row_version INTEGER NOT NULL,
    PRIMARY KEY (lease_name),
    CONSTRAINT ck_ops_scheduler_lease_fencing_token CHECK (fencing_token >= 0)
)""",
    """CREATE TABLE ops_trading_control (
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    armed BOOL NOT NULL,
    kill_switch_level VARCHAR(32) NOT NULL,
    owner_runtime_instance_id BINARY(16),
    acquired_at DATETIME,
    expires_at DATETIME,
    fencing_token INTEGER NOT NULL,
    row_version INTEGER NOT NULL,
    PRIMARY KEY (scope_type, scope_key),
    CONSTRAINT ck_ops_trading_control_scope CHECK (scope_type <> '' AND scope_key <> ''),
    CONSTRAINT ck_ops_trading_control_kill_switch CHECK (kill_switch_level IN ('NONE', 'BLOCK_NEW_EXPOSURE', 'EMERGENCY')),
    CONSTRAINT ck_ops_trading_control_fencing_token CHECK (fencing_token >= 0)
)""",
    """CREATE TABLE risk_budget_anchor (
    id BINARY(16) NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    scope_key VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    currency VARCHAR(3) NOT NULL,
    position_risk_amount NUMERIC(38, 18) NOT NULL,
    remaining_reservation_amount NUMERIC(38, 18) NOT NULL,
    hard_limit_amount NUMERIC(38, 18) NOT NULL,
    row_version BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_risk_budget_anchor_amounts CHECK ((position_risk_amount >= 0) and (remaining_reservation_amount >= 0) and (hard_limit_amount >= 0) and (row_version >= 0)),
    CONSTRAINT uq_risk_budget_anchor_scope UNIQUE (scope_type, scope_key, currency),
    CONSTRAINT ck_risk_budget_anchor_scope CHECK (scope_type IN ('GLOBAL', 'ACCOUNT'))
)""",
    """CREATE TABLE risk_decision (
    id BINARY(16) NOT NULL,
    order_intent_id BINARY(16) NOT NULL,
    policy_version_id BINARY(16) NOT NULL,
    risk_snapshot_id BINARY(16) NOT NULL,
    outcome VARCHAR(24) NOT NULL,
    requested_quantity NUMERIC(38, 18) NOT NULL,
    approved_quantity NUMERIC(38, 18) NOT NULL,
    approved_limit_price NUMERIC(38, 18),
    reserved_risk_amount NUMERIC(38, 18) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    reason_codes JSON NOT NULL,
    decision_hash BINARY(32) NOT NULL,
    decided_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_risk_decision_id_intent UNIQUE (id, order_intent_id),
    CONSTRAINT fk_risk_decision_intent FOREIGN KEY(order_intent_id) REFERENCES exec_order_intent (id),
    CONSTRAINT fk_risk_decision_policy_version FOREIGN KEY(policy_version_id) REFERENCES risk_policy_version (id),
    CONSTRAINT fk_risk_decision_snapshot FOREIGN KEY(risk_snapshot_id) REFERENCES risk_snapshot (id),
    CONSTRAINT ck_risk_decision_outcome_observed CHECK ((outcome in ('APPROVE','REJECT','REDUCE','OBSERVED_BLOCKING')) and ((outcome <> 'OBSERVED_BLOCKING') or ((approved_quantity = 0) and (reserved_risk_amount > 0)))),
    CONSTRAINT uq_risk_decision_order_intent UNIQUE (order_intent_id),
    CONSTRAINT ck_risk_decision_quantities CHECK (requested_quantity > 0 AND approved_quantity >= 0 AND approved_quantity <= requested_quantity AND reserved_risk_amount >= 0)
)""",
    """CREATE TABLE risk_policy (
    id BINARY(16) NOT NULL,
    code VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    active BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_risk_policy_code UNIQUE (code)
)""",
    """CREATE TABLE strategy_definition (
    id BINARY(16) NOT NULL,
    code VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    research_only BOOL NOT NULL,
    configuration_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_strategy_definition_code UNIQUE (code)
)""",
    """CREATE TABLE strategy_source_reference (
    id BINARY(16) NOT NULL,
    source_key VARCHAR(128) NOT NULL,
    verified BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_strategy_source_reference_key UNIQUE (source_key)
)""",
    """CREATE TABLE backoffice_bootstrap_authority (
    id BINARY(16) NOT NULL,
    scope_key VARCHAR(16) COLLATE ascii_bin NOT NULL,
    oauth_client_id_secret_id BINARY(16) NOT NULL,
    oauth_client_secret_secret_id BINARY(16) NOT NULL,
    second_password_version_id BINARY(16) NOT NULL,
    bootstrap_digest BINARY(32) NOT NULL,
    completed_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_backoffice_bootstrap_scope UNIQUE (scope_key),
    CONSTRAINT ck_backoffice_bootstrap_scope CHECK (scope_key = 'PRIMARY' AND oauth_client_id_secret_id <> oauth_client_secret_secret_id AND OCTET_LENGTH(bootstrap_digest) = 32),
    CONSTRAINT fk_backoffice_bootstrap_oauth_client_id FOREIGN KEY(oauth_client_id_secret_id) REFERENCES backoffice_secret_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backoffice_bootstrap_oauth_client_secret FOREIGN KEY(oauth_client_secret_secret_id) REFERENCES backoffice_secret_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backoffice_bootstrap_second_password FOREIGN KEY(second_password_version_id) REFERENCES backoffice_second_password_version (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE backoffice_secret_activation (
    id BINARY(16) NOT NULL,
    logical_name VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    secret_version_id BINARY(16) NOT NULL,
    previous_activation_id BINARY(16),
    activated_at DATETIME NOT NULL,
    deactivated_at DATETIME,
    active_marker VARCHAR(6) COLLATE ascii_bin,
    PRIMARY KEY (id),
    CONSTRAINT uq_backoffice_secret_activation_version UNIQUE (secret_version_id),
    CONSTRAINT uq_backoffice_secret_activation_active_name UNIQUE (logical_name, active_marker),
    CONSTRAINT uq_backoffice_secret_activation_exact_scope UNIQUE (id, logical_name),
    CONSTRAINT ck_backoffice_secret_activation_state CHECK ((deactivated_at IS NULL AND active_marker = 'ACTIVE') OR (deactivated_at > activated_at AND active_marker IS NULL)),
    CONSTRAINT fk_backoffice_secret_activation_version FOREIGN KEY(secret_version_id, logical_name) REFERENCES backoffice_secret_version (id, logical_name) ON DELETE RESTRICT,
    CONSTRAINT fk_backoffice_secret_activation_previous FOREIGN KEY(previous_activation_id, logical_name) REFERENCES backoffice_secret_activation (id, logical_name) ON DELETE RESTRICT
)""",
    """CREATE TABLE core_exchange (
    id BINARY(16) NOT NULL,
    market_id BINARY(16) NOT NULL,
    code VARCHAR(32) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_core_exchange_market_code UNIQUE (market_id, code),
    CONSTRAINT ck_core_exchange_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_core_exchange_market FOREIGN KEY(market_id) REFERENCES core_market (id)
)""",
    """CREATE TABLE exec_account (
    id BINARY(16) NOT NULL,
    broker_id BINARY(16) NOT NULL,
    account_alias VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    environment VARCHAR(16) NOT NULL,
    secret_reference VARCHAR(512) NOT NULL,
    enabled BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_exec_account_id_broker UNIQUE (id, broker_id),
    CONSTRAINT fk_exec_account_broker FOREIGN KEY(broker_id) REFERENCES exec_broker (id),
    CONSTRAINT uq_exec_account_environment UNIQUE (broker_id, account_alias, environment),
    CONSTRAINT uq_exec_account_id_broker_environment UNIQUE (id, broker_id, environment),
    CONSTRAINT ck_exec_account_environment CHECK (environment IN ('PAPER', 'LIVE'))
)""",
    """CREATE TABLE exec_broker_order_link (
    id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    broker_id BINARY(16) NOT NULL,
    broker_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    link_sequence BIGINT NOT NULL,
    exposure_bearing BOOL NOT NULL,
    status VARCHAR(24) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_exec_broker_link_sequence UNIQUE (order_id, link_sequence),
    CONSTRAINT fk_exec_broker_link_broker FOREIGN KEY(broker_id) REFERENCES exec_broker (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_broker_link_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT uq_exec_broker_link_broker_order UNIQUE (broker_id, broker_order_id)
)""",
    """CREATE TABLE exec_order_command_authority (
    order_id BINARY(16) NOT NULL,
    authority_class VARCHAR(32) NOT NULL,
    PRIMARY KEY (order_id, authority_class),
    CONSTRAINT fk_exec_order_command_authority_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_order_command_authority_class CHECK (authority_class in ('SUBMIT_NEW_EXPOSURE','SUBMIT_STRICT_REDUCTION','CANCEL','REPLACE_NON_INCREASING')),
    CONSTRAINT uq_exec_order_command_authority UNIQUE (order_id, authority_class)
)""",
    """CREATE TABLE exec_order_event (
    id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    aggregate_version BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    raw_status VARCHAR(128) NOT NULL,
    occurred_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_order_event_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT uq_exec_order_event_version UNIQUE (order_id, aggregate_version)
)""",
    """CREATE TABLE exec_order_status_watermark (
    order_id BINARY(16) NOT NULL,
    source_partition VARCHAR(128) COLLATE ascii_bin NOT NULL,
    last_contiguous_sequence BIGINT NOT NULL,
    PRIMARY KEY (order_id, source_partition),
    CONSTRAINT fk_exec_order_status_watermark_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_order_status_watermark_sequence CHECK (last_contiguous_sequence >= 0),
    CONSTRAINT uq_exec_order_status_watermark UNIQUE (order_id, source_partition)
)""",
    """CREATE TABLE exec_paper_order (
    command_id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    account_alias VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
    market VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_style VARCHAR(16) NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    limit_price NUMERIC(38, 18),
    signal_at DATETIME NOT NULL,
    timeframe_seconds BIGINT NOT NULL,
    fee_per_unit NUMERIC(38, 18) NOT NULL,
    slippage_per_unit NUMERIC(38, 18) NOT NULL,
    command_digest VARBINARY(32) NOT NULL,
    staged_at DATETIME NOT NULL,
    status VARCHAR(24),
    filled_quantity NUMERIC(38, 18),
    remaining_quantity NUMERIC(38, 18),
    fill_price NUMERIC(38, 18),
    fee NUMERIC(38, 18),
    slippage_cost NUMERIC(38, 18),
    filled_at DATETIME,
    reason_code VARCHAR(64),
    source_digest VARBINARY(32),
    PRIMARY KEY (command_id),
    CONSTRAINT fk_exec_paper_order_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_paper_order_terms CHECK (market IN ('KRX_CASH', 'US_CASH', 'BINANCE_USDM') AND side IN ('BUY', 'SELL') AND order_style IN ('MARKET', 'LIMIT') AND quantity > 0 AND timeframe_seconds > 0 AND fee_per_unit >= 0 AND slippage_per_unit >= 0),
    CONSTRAINT ck_exec_paper_order_digest CHECK (OCTET_LENGTH(command_digest) = 32),
    CONSTRAINT ck_exec_paper_order_receipt CHECK ((status IS NULL AND filled_quantity IS NULL AND remaining_quantity IS NULL AND fee IS NULL AND slippage_cost IS NULL) OR (status IN ('FILLED', 'PARTIALLY_FILLED', 'NO_FILL', 'UNKNOWN') AND filled_quantity >= 0 AND remaining_quantity >= 0 AND fee >= 0 AND slippage_cost >= 0 AND filled_quantity + remaining_quantity = quantity)),
    CONSTRAINT ck_exec_paper_order_fill CHECK ((status IS NULL) OR (status = 'NO_FILL' AND fill_price IS NULL AND filled_at IS NULL AND reason_code IS NOT NULL AND filled_quantity = 0) OR (status IN ('FILLED', 'PARTIALLY_FILLED') AND fill_price > 0 AND filled_at IS NOT NULL AND filled_quantity > 0))
)""",
    """CREATE TABLE risk_policy_version (
    id BINARY(16) NOT NULL,
    policy_id BINARY(16) NOT NULL,
    version VARCHAR(64) NOT NULL,
    active BOOL NOT NULL,
    max_total_risk NUMERIC(38, 18),
    max_position_value NUMERIC(38, 18),
    max_daily_loss NUMERIC(38, 18),
    max_drawdown NUMERIC(38, 18),
    normal_risk_fraction NUMERIC(20, 10),
    a_candidate_risk_fraction NUMERIC(20, 10),
    a_risk_fraction NUMERIC(20, 10),
    absolute_trade_risk_fraction NUMERIC(20, 10),
    daily_loss_fraction NUMERIC(20, 10),
    weekly_loss_fraction NUMERIC(20, 10),
    max_consecutive_losses BIGINT,
    max_open_structural_risk_fraction NUMERIC(20, 10),
    account_age_seconds BIGINT,
    risk_age_seconds BIGINT,
    quote_age_seconds BIGINT,
    provider_age_seconds BIGINT,
    stream_gap_age_seconds BIGINT,
    completed_intraday_bar_arrival_seconds BIGINT,
    daily_requires_authoritative_close BOOL,
    max_account_snapshot_age_seconds BIGINT,
    max_risk_snapshot_age_seconds BIGINT,
    max_market_data_age_seconds BIGINT,
    max_provider_fact_age_seconds BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uq_risk_policy_version UNIQUE (policy_id, version),
    CONSTRAINT fk_risk_policy_version_policy FOREIGN KEY(policy_id) REFERENCES risk_policy (id),
    CONSTRAINT ck_risk_policy_version_limits_non_negative CHECK ((max_total_risk IS NULL AND max_position_value IS NULL AND max_daily_loss IS NULL AND max_drawdown IS NULL) OR (max_total_risk >= 0 AND max_position_value >= 0 AND max_daily_loss >= 0 AND max_drawdown >= 0)),
    CONSTRAINT ck_risk_policy_version_age_seconds CHECK ((max_account_snapshot_age_seconds IS NULL OR max_account_snapshot_age_seconds >= 0) AND (max_risk_snapshot_age_seconds IS NULL OR max_risk_snapshot_age_seconds >= 0) AND (max_market_data_age_seconds IS NULL OR max_market_data_age_seconds >= 0) AND (max_provider_fact_age_seconds IS NULL OR max_provider_fact_age_seconds >= 0)),
    CONSTRAINT ck_risk_policy_version_v6_shape CHECK ((normal_risk_fraction IS NULL AND a_candidate_risk_fraction IS NULL AND a_risk_fraction IS NULL AND absolute_trade_risk_fraction IS NULL AND daily_loss_fraction IS NULL AND weekly_loss_fraction IS NULL AND max_consecutive_losses IS NULL AND max_open_structural_risk_fraction IS NULL AND account_age_seconds IS NULL AND risk_age_seconds IS NULL AND quote_age_seconds IS NULL AND provider_age_seconds IS NULL AND stream_gap_age_seconds IS NULL AND completed_intraday_bar_arrival_seconds IS NULL AND daily_requires_authoritative_close IS NULL AND max_total_risk IS NOT NULL AND max_position_value IS NOT NULL AND max_daily_loss IS NOT NULL AND max_drawdown IS NOT NULL) OR (normal_risk_fraction IS NOT NULL AND a_risk_fraction IS NOT NULL AND absolute_trade_risk_fraction IS NOT NULL AND daily_loss_fraction IS NOT NULL AND weekly_loss_fraction IS NOT NULL AND max_consecutive_losses IS NOT NULL AND max_open_structural_risk_fraction IS NOT NULL AND account_age_seconds IS NOT NULL AND risk_age_seconds IS NOT NULL AND quote_age_seconds IS NOT NULL AND provider_age_seconds IS NOT NULL AND completed_intraday_bar_arrival_seconds IS NOT NULL AND daily_requires_authoritative_close IS NOT NULL AND max_total_risk IS NULL AND max_position_value IS NULL AND max_daily_loss IS NULL AND max_drawdown IS NULL AND max_account_snapshot_age_seconds IS NULL AND max_risk_snapshot_age_seconds IS NULL AND max_market_data_age_seconds IS NULL AND max_provider_fact_age_seconds IS NULL)),
    CONSTRAINT ck_risk_policy_version_v6_bounds CHECK (normal_risk_fraction IS NULL OR (normal_risk_fraction > 0 AND normal_risk_fraction <= 1 AND (a_candidate_risk_fraction IS NULL OR (a_candidate_risk_fraction > 0 AND a_candidate_risk_fraction <= 1)) AND a_risk_fraction > 0 AND a_risk_fraction <= 1 AND absolute_trade_risk_fraction > 0 AND absolute_trade_risk_fraction <= 1 AND normal_risk_fraction <= absolute_trade_risk_fraction AND (a_candidate_risk_fraction IS NULL OR a_candidate_risk_fraction <= absolute_trade_risk_fraction) AND a_risk_fraction <= absolute_trade_risk_fraction AND daily_loss_fraction > 0 AND daily_loss_fraction <= 1 AND weekly_loss_fraction > 0 AND weekly_loss_fraction <= 1 AND max_consecutive_losses > 0 AND max_open_structural_risk_fraction > 0 AND max_open_structural_risk_fraction <= 1 AND account_age_seconds > 0 AND risk_age_seconds > 0 AND quote_age_seconds > 0 AND provider_age_seconds > 0 AND (stream_gap_age_seconds IS NULL OR stream_gap_age_seconds > 0) AND completed_intraday_bar_arrival_seconds > 0))
)""",
    """CREATE TABLE strategy_version (
    id BINARY(16) NOT NULL,
    definition_id BINARY(16) NOT NULL,
    version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    research_only BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_strategy_version_definition FOREIGN KEY(definition_id) REFERENCES strategy_definition (id),
    CONSTRAINT uq_strategy_version_number UNIQUE (definition_id, version),
    CONSTRAINT ck_strategy_version_status CHECK (status IN ('SHADOW', 'LIVE_APPROVED', 'RETIRED')),
    CONSTRAINT ck_strategy_version_research_only CHECK (NOT (research_only AND status = 'LIVE_APPROVED'))
)""",
    """CREATE TABLE core_instrument (
    id BINARY(16) NOT NULL,
    exchange_id BINARY(16) NOT NULL,
    code VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(256) NOT NULL,
    instrument_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_core_instrument_exchange_code UNIQUE (exchange_id, code),
    CONSTRAINT ck_core_instrument_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_core_instrument_exchange FOREIGN KEY(exchange_id) REFERENCES core_exchange (id)
)""",
    """CREATE TABLE exec_account_risk_policy_binding (
    id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    policy_version_id BINARY(16) NOT NULL,
    previous_binding_id BINARY(16),
    currency VARCHAR(3),
    settlement_asset VARCHAR(16) COLLATE ascii_bin,
    account_scope_hash VARBINARY(32) NOT NULL,
    activated_at DATETIME NOT NULL,
    deactivated_at DATETIME,
    active_marker VARCHAR(6) COLLATE utf8mb4_bin,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_account_policy_binding_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_account_policy_binding_version FOREIGN KEY(policy_version_id) REFERENCES risk_policy_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_account_policy_binding_previous FOREIGN KEY(previous_binding_id) REFERENCES exec_account_risk_policy_binding (id) ON DELETE RESTRICT,
    CONSTRAINT uq_exec_account_policy_binding_target UNIQUE (account_id, policy_version_id),
    CONSTRAINT uq_exec_account_policy_binding_exact_target UNIQUE (id, account_id, policy_version_id),
    CONSTRAINT uq_exec_account_policy_binding_active_scope UNIQUE (account_id, currency, active_marker),
    CONSTRAINT uq_exec_account_policy_binding_active_settlement UNIQUE (account_id, settlement_asset, active_marker),
    CONSTRAINT ck_exec_account_policy_binding_scope CHECK (((currency IN ('KRW', 'USD') AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset = 'USDT')) AND OCTET_LENGTH(account_scope_hash) = 32),
    CONSTRAINT ck_exec_account_policy_binding_state CHECK ((deactivated_at IS NULL AND active_marker = 'ACTIVE') OR (deactivated_at > activated_at AND active_marker IS NULL))
)""",
    """CREATE TABLE exec_account_snapshot (
    id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    as_of DATETIME NOT NULL,
    currency VARCHAR(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_account_snapshot_account FOREIGN KEY(account_id) REFERENCES exec_account (id)
)""",
    """CREATE TABLE exec_broker_order_status_event (
    id BINARY(16) NOT NULL,
    order_id BINARY(16),
    broker_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    source_partition VARCHAR(128) COLLATE ascii_bin NOT NULL,
    dedupe_key VARCHAR(256) COLLATE ascii_bin NOT NULL,
    canonical_payload_hash BINARY(32) NOT NULL,
    broker_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    broker_client_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    raw_status VARCHAR(128) NOT NULL,
    requested_quantity NUMERIC(38, 18) NOT NULL,
    cumulative_filled_quantity NUMERIC(38, 18) NOT NULL,
    source_sequence BIGINT,
    occurred_at DATETIME NOT NULL,
    observed_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_exec_broker_status_identity UNIQUE (broker_id, account_id, source_partition, dedupe_key),
    CONSTRAINT fk_exec_broker_status_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_broker_status_broker FOREIGN KEY(broker_id) REFERENCES exec_broker (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_broker_status_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE exec_provider_account_binding (
    id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    broker_id BINARY(16) NOT NULL,
    provider_code VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
    environment VARCHAR(16) NOT NULL,
    account_seq BIGINT,
    revision BIGINT NOT NULL,
    observed_at DATETIME NOT NULL,
    active BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_exec_provider_account_binding_revision UNIQUE (account_id, provider_code, environment, revision),
    CONSTRAINT uq_exec_provider_account_binding_id_account UNIQUE (id, account_id),
    CONSTRAINT uq_exec_provider_account_binding_exact_scope UNIQUE (id, account_id, provider_code, environment),
    CONSTRAINT ck_exec_provider_account_binding_scope CHECK (provider_code IN ('TOSS', 'KIS', 'BINANCE') AND environment IN ('PAPER', 'LIVE') AND revision > 0 AND ((provider_code = 'TOSS' AND account_seq > 0) OR (provider_code IN ('KIS', 'BINANCE') AND account_seq IS NULL))),
    CONSTRAINT fk_exec_provider_account_binding_account FOREIGN KEY(account_id, broker_id, environment) REFERENCES exec_account (id, broker_id, environment) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_provider_account_binding_broker FOREIGN KEY(broker_id, provider_code) REFERENCES exec_broker (id, code) ON DELETE RESTRICT
)""",
    """CREATE TABLE exec_reconciliation_run (
    id BINARY(16) NOT NULL,
    broker_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    started_at DATETIME NOT NULL,
    completed_at DATETIME,
    status VARCHAR(24) NOT NULL,
    snapshot_hash BINARY(32) NOT NULL,
    complete BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_reconciliation_run_account_broker FOREIGN KEY(account_id, broker_id) REFERENCES exec_account (id, broker_id),
    CONSTRAINT ck_exec_reconciliation_run_completion CHECK (((status = 'RUNNING') and (complete = 0) and (completed_at is null)) or ((status = 'SUCCEEDED') and (complete = 1) and (completed_at is not null)) or ((status = 'FAILED') and (complete = 0) and (completed_at is not null))),
    CONSTRAINT ck_exec_reconciliation_run_status CHECK (status in ('RUNNING','SUCCEEDED','FAILED')),
    CONSTRAINT uq_exec_reconciliation_run_identity UNIQUE (broker_id, account_id, snapshot_hash),
    CONSTRAINT uq_exec_reconciliation_run_id_account UNIQUE (id, account_id),
    CONSTRAINT uq_exec_reconciliation_run_id_account_broker UNIQUE (id, account_id, broker_id)
)""",
    """CREATE TABLE risk_budget_reservation (
    id BINARY(16) NOT NULL,
    risk_decision_id BINARY(16) NOT NULL,
    order_intent_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    currency VARCHAR(3),
    settlement_asset VARCHAR(16),
    initial_risk_amount NUMERIC(38, 18) NOT NULL,
    consumed_risk_amount NUMERIC(38, 18) NOT NULL,
    remaining_risk_amount NUMERIC(38, 18) NOT NULL,
    released_risk_amount NUMERIC(38, 18) NOT NULL,
    status VARCHAR(24) NOT NULL,
    active_marker VARCHAR(1) GENERATED ALWAYS AS (CASE WHEN status IN ('ACTIVE', 'PARTIALLY_CONSUMED') THEN 'Y' ELSE NULL END),
    expires_at DATETIME NOT NULL,
    release_reason VARCHAR(128),
    PRIMARY KEY (id),
    CONSTRAINT fk_risk_budget_reservation_account FOREIGN KEY(account_id) REFERENCES exec_account (id),
    CONSTRAINT fk_risk_budget_reservation_decision FOREIGN KEY(risk_decision_id) REFERENCES risk_decision (id),
    CONSTRAINT fk_risk_budget_reservation_intent FOREIGN KEY(order_intent_id) REFERENCES exec_order_intent (id),
    CONSTRAINT ck_risk_budget_reservation_amounts_non_negative CHECK ((initial_risk_amount >= 0) and (consumed_risk_amount >= 0) and (remaining_risk_amount >= 0) and (released_risk_amount >= 0)),
    CONSTRAINT ck_risk_budget_reservation_status CHECK (status in ('ACTIVE','PARTIALLY_CONSUMED','CONSUMED','RELEASED')),
    CONSTRAINT uq_risk_budget_reservation_decision UNIQUE (risk_decision_id),
    CONSTRAINT uq_risk_budget_reservation_active_intent UNIQUE (order_intent_id, active_marker),
    CONSTRAINT ck_risk_budget_reservation_accounting CHECK (consumed_risk_amount + remaining_risk_amount + released_risk_amount = initial_risk_amount),
    CONSTRAINT ck_risk_budget_reservation_denomination CHECK ((currency IS NOT NULL AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset IS NOT NULL))
)""",
    """CREATE TABLE strategy_david_v6_manifest (
    id BINARY(16) NOT NULL,
    strategy_version_id BINARY(16) NOT NULL,
    strategy_code VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    strategy_version VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
    source_sha256 VARBINARY(32) NOT NULL,
    design_sha256 VARBINARY(32) NOT NULL,
    configuration_hash VARBINARY(32) NOT NULL,
    registered_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_strategy_david_v6_manifest_version_hashes UNIQUE (strategy_version_id, source_sha256, configuration_hash),
    CONSTRAINT uq_strategy_david_v6_manifest_exact_version UNIQUE (id, strategy_version_id),
    CONSTRAINT ck_strategy_david_v6_manifest_identity CHECK (strategy_code = 'DAVID_TRULLAS_V6' AND strategy_version = 'v6.0-op-20260824.1'),
    CONSTRAINT ck_strategy_david_v6_manifest_hashes CHECK (OCTET_LENGTH(source_sha256) = 32 AND OCTET_LENGTH(design_sha256) = 32 AND OCTET_LENGTH(configuration_hash) = 32),
    CONSTRAINT fk_strategy_david_v6_manifest_version FOREIGN KEY(strategy_version_id) REFERENCES strategy_version (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE strategy_feature_schema (
    id BINARY(16) NOT NULL,
    strategy_version_id BINARY(16) NOT NULL,
    schema_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_strategy_feature_schema_version FOREIGN KEY(strategy_version_id) REFERENCES strategy_version (id)
)""",
    """CREATE TABLE strategy_rule (
    id BINARY(16) NOT NULL,
    strategy_version_id BINARY(16) NOT NULL,
    rule_key VARCHAR(128) NOT NULL,
    hard_rule BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_strategy_rule_version FOREIGN KEY(strategy_version_id) REFERENCES strategy_version (id)
)""",
    """CREATE TABLE strategy_setup (
    id BINARY(16) NOT NULL,
    strategy_version_id BINARY(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_strategy_setup_version FOREIGN KEY(strategy_version_id) REFERENCES strategy_version (id)
)""",
    """CREATE TABLE binance_usdm_reconciliation_run (
    id BINARY(16) NOT NULL,
    binding_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    provider_code VARCHAR(16) COLLATE ascii_bin NOT NULL,
    market_code VARCHAR(16) COLLATE ascii_bin NOT NULL,
    symbol VARCHAR(16) COLLATE ascii_bin NOT NULL,
    settlement_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    provider_as_of DATETIME(6) NOT NULL,
    started_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6) NOT NULL,
    result VARCHAR(16) COLLATE ascii_bin NOT NULL,
    balance_fact_count BIGINT NOT NULL,
    position_fact_count BIGINT NOT NULL,
    order_fact_count BIGINT NOT NULL,
    algo_order_fact_count BIGINT NOT NULL,
    trade_fact_count BIGINT NOT NULL,
    income_fact_count BIGINT NOT NULL,
    configuration_fact_count BIGINT NOT NULL,
    fact_digest VARBINARY(32) NOT NULL,
    blockers JSON NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_reconciliation_identity UNIQUE (binding_id, provider_as_of),
    CONSTRAINT ck_binance_usdm_reconciliation_scope CHECK (provider_code = 'BINANCE' AND market_code = 'USD-M' AND symbol = 'BTCUSDT' AND settlement_asset = 'USDT'),
    CONSTRAINT ck_binance_usdm_reconciliation_values CHECK (provider_as_of <= started_at AND started_at < completed_at AND balance_fact_count >= 0 AND position_fact_count >= 0 AND order_fact_count >= 0 AND algo_order_fact_count >= 0 AND trade_fact_count >= 0 AND income_fact_count >= 0 AND configuration_fact_count >= 0 AND OCTET_LENGTH(fact_digest) = 32),
    CONSTRAINT ck_binance_usdm_reconciliation_result CHECK ((result = 'COMPLETE' AND balance_fact_count >= 1 AND position_fact_count >= 1 AND configuration_fact_count = 1 AND JSON_LENGTH(blockers) = 0) OR (result = 'PARTIAL' AND JSON_LENGTH(blockers) > 0)),
    CONSTRAINT fk_binance_usdm_reconciliation_binding FOREIGN KEY(binding_id, account_id) REFERENCES exec_provider_account_binding (id, account_id) ON DELETE RESTRICT
)""",
    """CREATE TABLE exec_broker_execution_watermark (
    id BINARY(16) NOT NULL,
    broker_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    source_partition VARCHAR(128) COLLATE ascii_bin NOT NULL,
    contiguous_through_sequence BIGINT,
    has_gap BOOL NOT NULL,
    covered_from_at DATETIME,
    covered_through_at DATETIME,
    pagination_complete BOOL NOT NULL,
    query_fingerprint BINARY(32) NOT NULL,
    evidence_hash BINARY(32) NOT NULL,
    expires_at DATETIME NOT NULL,
    row_version BIGINT NOT NULL,
    reconciliation_run_id BINARY(16),
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_execution_watermark_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_execution_watermark_broker FOREIGN KEY(broker_id) REFERENCES exec_broker (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_execution_watermark_reconciliation_run FOREIGN KEY(reconciliation_run_id) REFERENCES exec_reconciliation_run (id) ON DELETE RESTRICT,
    CONSTRAINT uq_exec_execution_watermark_partition UNIQUE (broker_id, account_id, source_partition)
)""",
    """CREATE TABLE exec_cash_snapshot (
    id BINARY(16) NOT NULL,
    account_snapshot_id BINARY(16) NOT NULL,
    amount NUMERIC(38, 18) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_cash_snapshot_account_snapshot FOREIGN KEY(account_snapshot_id) REFERENCES exec_account_snapshot (id)
)""",
    """CREATE TABLE exec_fill (
    id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    broker_id BINARY(16) NOT NULL,
    broker_execution_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    broker_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    source_partition VARCHAR(128) COLLATE ascii_bin NOT NULL,
    source_sequence BIGINT,
    side VARCHAR(8) NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    price NUMERIC(38, 18) NOT NULL,
    currency VARCHAR(3),
    settlement_asset VARCHAR(16),
    executed_at DATETIME NOT NULL,
    observed_at DATETIME NOT NULL,
    canonical_payload_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_fill_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_fill_broker FOREIGN KEY(broker_id) REFERENCES exec_broker (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_fill_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_fill_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_fill_positive_terms CHECK ((quantity > 0) and (price > 0)),
    CONSTRAINT uq_exec_fill_broker_execution UNIQUE (broker_id, account_id, broker_execution_id),
    CONSTRAINT ck_exec_fill_denomination CHECK ((currency IS NOT NULL AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset IS NOT NULL))
)""",
    """CREATE TABLE exec_order_command (
    id BINARY(16) NOT NULL,
    order_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    command_type VARCHAR(16) NOT NULL,
    command_sequence BIGINT NOT NULL,
    target_aggregate_version BIGINT NOT NULL,
    idempotency_key VARCHAR(256) COLLATE ascii_bin NOT NULL,
    canonical_payload_hash BINARY(32) NOT NULL,
    submit_once_marker VARCHAR(1) GENERATED ALWAYS AS (CASE WHEN command_type = 'SUBMIT' THEN 'Y' ELSE NULL END),
    broker_client_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    target_broker_order_id VARCHAR(128) COLLATE ascii_bin,
    replaces_command_id BINARY(16),
    origin_type VARCHAR(16) NOT NULL,
    authority_class VARCHAR(32) NOT NULL,
    owner_runtime_instance_id BINARY(16),
    fencing_token BIGINT NOT NULL,
    not_after DATETIME NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_style VARCHAR(16) NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    limit_price NUMERIC(38, 18),
    time_in_force VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    dispatch_attempted_at DATETIME,
    result_state VARCHAR(24),
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_order_command_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_command_authority FOREIGN KEY(order_id, authority_class) REFERENCES exec_order_command_authority (order_id, authority_class) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_command_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_command_order FOREIGN KEY(order_id) REFERENCES exec_order (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_order_command_replaces FOREIGN KEY(replaces_command_id) REFERENCES exec_order_command (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_order_command_authority_terms CHECK (((command_type = 'SUBMIT') and (authority_class in ('SUBMIT_NEW_EXPOSURE','SUBMIT_STRICT_REDUCTION'))) or ((command_type = 'CANCEL') and (authority_class = 'CANCEL')) or ((command_type = 'REPLACE') and (authority_class = 'REPLACE_NON_INCREASING'))),
    CONSTRAINT ck_exec_order_command_terms CHECK ((quantity > 0) and (target_aggregate_version >= 0)),
    CONSTRAINT ck_exec_order_command_type CHECK (command_type in ('SUBMIT','CANCEL','REPLACE')),
    CONSTRAINT uq_exec_order_command_sequence UNIQUE (order_id, command_sequence),
    CONSTRAINT uq_exec_order_command_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_exec_order_submit_once UNIQUE (order_id, submit_once_marker)
)""",
    """CREATE TABLE exec_position (
    id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    average_cost NUMERIC(38, 18) NOT NULL,
    currency VARCHAR(3),
    settlement_asset VARCHAR(16),
    observed_at DATETIME NOT NULL,
    blocking_risk BOOL NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_exec_position_account_instrument UNIQUE (account_id, instrument_id),
    CONSTRAINT fk_exec_position_account FOREIGN KEY(account_id) REFERENCES exec_account (id),
    CONSTRAINT fk_exec_position_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id),
    CONSTRAINT ck_exec_position_negative_blocking CHECK (quantity >= 0 OR blocking_risk),
    CONSTRAINT ck_exec_position_denomination CHECK ((quantity = 0 AND currency IS NULL AND settlement_asset IS NULL) OR (currency IS NOT NULL AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset IS NOT NULL))
)""",
    """CREATE TABLE risk_snapshot (
    id BINARY(16) NOT NULL,
    account_snapshot_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    as_of DATETIME NOT NULL,
    currency VARCHAR(3),
    settlement_asset VARCHAR(16),
    equity NUMERIC(38, 18) NOT NULL,
    cash NUMERIC(38, 18) NOT NULL,
    gross_exposure NUMERIC(38, 18) NOT NULL,
    net_exposure NUMERIC(38, 18) NOT NULL,
    open_risk NUMERIC(38, 18) NOT NULL,
    daily_realized_pnl NUMERIC(38, 18) NOT NULL,
    daily_unrealized_pnl NUMERIC(38, 18) NOT NULL,
    drawdown NUMERIC(38, 18) NOT NULL,
    position_hash BINARY(32) NOT NULL,
    open_order_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_risk_snapshot_account FOREIGN KEY(account_id) REFERENCES exec_account (id),
    CONSTRAINT fk_risk_snapshot_account_snapshot FOREIGN KEY(account_snapshot_id) REFERENCES exec_account_snapshot (id),
    CONSTRAINT ck_risk_snapshot_denomination CHECK ((currency IS NOT NULL AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset IS NOT NULL))
)""",
    """CREATE TABLE strategy_feature_snapshot (
    id BINARY(16) NOT NULL,
    feature_schema_id BINARY(16) NOT NULL,
    payload_hash BINARY(32) NOT NULL,
    available_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_strategy_feature_snapshot_schema FOREIGN KEY(feature_schema_id) REFERENCES strategy_feature_schema (id)
)""",
    """CREATE TABLE strategy_rule_source (
    rule_id BINARY(16) NOT NULL,
    source_reference_id BINARY(16) NOT NULL,
    PRIMARY KEY (rule_id, source_reference_id),
    CONSTRAINT fk_strategy_rule_source_reference FOREIGN KEY(source_reference_id) REFERENCES strategy_source_reference (id),
    CONSTRAINT fk_strategy_rule_source_rule FOREIGN KEY(rule_id) REFERENCES strategy_rule (id)
)""",
    """CREATE TABLE toss_us_reconciliation_run (
    id BINARY(16) NOT NULL,
    binding_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    provider_code VARCHAR(16) COLLATE ascii_bin NOT NULL,
    market_country VARCHAR(2) COLLATE ascii_bin NOT NULL,
    settlement_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    provider_as_of DATETIME NOT NULL,
    started_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    completed_at DATETIME,
    result VARCHAR(16) COLLATE ascii_bin NOT NULL,
    holdings_page_count BIGINT NOT NULL,
    open_order_page_count BIGINT NOT NULL,
    closed_order_page_count BIGINT NOT NULL,
    missing_page_count BIGINT NOT NULL,
    cash_fact_count BIGINT NOT NULL,
    position_fact_count BIGINT NOT NULL,
    order_fact_count BIGINT NOT NULL,
    fact_digest VARBINARY(32),
    blockers JSON NOT NULL,
    checkpoint JSON,
    PRIMARY KEY (id),
    CONSTRAINT uq_toss_us_reconciliation_identity UNIQUE (binding_id, provider_as_of),
    CONSTRAINT ck_toss_us_reconciliation_scope CHECK (provider_code = 'TOSS' AND market_country = 'US' AND settlement_asset = 'USD'),
    CONSTRAINT ck_toss_us_reconciliation_values CHECK (provider_as_of <= started_at AND started_at <= updated_at AND (completed_at IS NULL OR updated_at <= completed_at) AND holdings_page_count >= 0 AND open_order_page_count >= 0 AND closed_order_page_count >= 0 AND missing_page_count >= 0 AND cash_fact_count >= 0 AND position_fact_count >= 0 AND order_fact_count >= 0 AND (fact_digest IS NULL OR OCTET_LENGTH(fact_digest) = 32)),
    CONSTRAINT ck_toss_us_reconciliation_result CHECK ((result = 'IN_PROGRESS' AND completed_at IS NULL AND fact_digest IS NULL AND checkpoint IS NOT NULL AND JSON_LENGTH(blockers) = 0) OR (result = 'COMPLETE' AND completed_at > started_at AND OCTET_LENGTH(fact_digest) = 32 AND checkpoint IS NULL AND missing_page_count = 0 AND holdings_page_count >= 1 AND open_order_page_count >= 1 AND closed_order_page_count >= 1 AND cash_fact_count = 1 AND JSON_LENGTH(blockers) = 0) OR (result = 'PARTIAL' AND completed_at > started_at AND OCTET_LENGTH(fact_digest) = 32 AND checkpoint IS NULL AND (missing_page_count > 0 OR holdings_page_count = 0 OR open_order_page_count = 0 OR closed_order_page_count = 0 OR cash_fact_count = 0 OR JSON_LENGTH(blockers) > 0))),
    CONSTRAINT fk_toss_us_reconciliation_binding FOREIGN KEY(binding_id, account_id) REFERENCES exec_provider_account_binding (id, account_id) ON DELETE RESTRICT
)""",
    """CREATE TABLE toss_us_recovery_lease (
    id BINARY(16) NOT NULL,
    binding_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    client_order_id VARCHAR(36) COLLATE ascii_bin NOT NULL,
    first_dispatch_at DATETIME NOT NULL,
    canonical_request_digest VARBINARY(32) NOT NULL,
    lease_owner BINARY(16) NOT NULL,
    lease_acquired_at DATETIME NOT NULL,
    lease_expires_at DATETIME NOT NULL,
    replay_count BIGINT NOT NULL,
    terminal_state VARCHAR(16) COLLATE ascii_bin NOT NULL,
    terminal_at DATETIME,
    provider_order_id VARCHAR(128) COLLATE ascii_bin,
    active_marker VARCHAR(6) COLLATE ascii_bin,
    PRIMARY KEY (id),
    CONSTRAINT uq_toss_us_recovery_client_order UNIQUE (binding_id, client_order_id),
    CONSTRAINT uq_toss_us_recovery_active_binding UNIQUE (binding_id, active_marker),
    CONSTRAINT ck_toss_us_recovery_lease_shape CHECK (CHAR_LENGTH(client_order_id) BETWEEN 1 AND 36 AND OCTET_LENGTH(canonical_request_digest) = 32 AND replay_count BETWEEN 0 AND 1 AND terminal_state IN ('OPEN', 'ACKNOWLEDGED', 'REJECTED', 'UNKNOWN', 'EXPIRED') AND ((terminal_state = 'OPEN' AND active_marker = 'ACTIVE' AND terminal_at IS NULL AND lease_acquired_at >= first_dispatch_at AND lease_expires_at > lease_acquired_at AND lease_expires_at <= DATE_ADD(first_dispatch_at, INTERVAL 600 SECOND)) OR (terminal_state <> 'OPEN' AND active_marker IS NULL AND terminal_at >= first_dispatch_at))),
    CONSTRAINT fk_toss_us_recovery_binding FOREIGN KEY(binding_id, account_id) REFERENCES exec_provider_account_binding (id, account_id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_algo_order_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    provider_algo_id BIGINT NOT NULL,
    client_algo_id VARCHAR(36) COLLATE ascii_bin NOT NULL,
    symbol VARCHAR(16) COLLATE ascii_bin NOT NULL,
    status VARCHAR(32) COLLATE ascii_bin NOT NULL,
    side VARCHAR(4) COLLATE ascii_bin NOT NULL,
    order_type VARCHAR(32) COLLATE ascii_bin NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    trigger_price NUMERIC(38, 18) NOT NULL,
    close_position BOOL NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_algo_identity UNIQUE (run_id, provider_algo_id),
    CONSTRAINT uq_binance_usdm_algo_client_identity UNIQUE (run_id, client_algo_id),
    CONSTRAINT ck_binance_usdm_algo_values CHECK (symbol = 'BTCUSDT' AND side IN ('BUY', 'SELL') AND quantity >= 0 AND trigger_price > 0),
    CONSTRAINT fk_binance_usdm_algo_order_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_balance_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    wallet_balance NUMERIC(38, 18) NOT NULL,
    available_balance NUMERIC(38, 18) NOT NULL,
    maximum_withdraw_amount NUMERIC(38, 18) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_balance_identity UNIQUE (run_id, asset),
    CONSTRAINT ck_binance_usdm_balance_values CHECK (asset = 'USDT' AND wallet_balance >= 0 AND available_balance >= 0 AND maximum_withdraw_amount >= 0 AND updated_at <= captured_at),
    CONSTRAINT fk_binance_usdm_balance_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_configuration_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    position_mode VARCHAR(16) COLLATE ascii_bin NOT NULL,
    margin_type VARCHAR(16) COLLATE ascii_bin NOT NULL,
    auto_add_margin BOOL NOT NULL,
    leverage BIGINT NOT NULL,
    can_trade BOOL NOT NULL,
    multi_assets_margin BOOL NOT NULL,
    transfer_out_enabled BOOL NOT NULL,
    maximum_notional NUMERIC(38, 18) NOT NULL,
    price_tick_size NUMERIC(38, 18) NOT NULL,
    minimum_quantity NUMERIC(38, 18) NOT NULL,
    quantity_step_size NUMERIC(38, 18) NOT NULL,
    minimum_notional NUMERIC(38, 18) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_configuration_identity UNIQUE (run_id),
    CONSTRAINT ck_binance_usdm_configuration_values CHECK (position_mode IN ('ONE_WAY', 'HEDGE') AND margin_type IN ('ISOLATED', 'CROSSED') AND leverage > 0 AND maximum_notional > 0 AND price_tick_size > 0 AND minimum_quantity > 0 AND quantity_step_size > 0 AND minimum_notional > 0),
    CONSTRAINT fk_binance_usdm_configuration_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_income_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    provider_transaction_id BIGINT NOT NULL,
    trade_id VARCHAR(64) COLLATE ascii_bin NOT NULL,
    symbol VARCHAR(16) COLLATE ascii_bin NOT NULL,
    income_type VARCHAR(32) COLLATE ascii_bin NOT NULL,
    income NUMERIC(38, 18) NOT NULL,
    asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_income_identity UNIQUE (run_id, provider_transaction_id),
    CONSTRAINT ck_binance_usdm_income_values CHECK (asset = 'USDT' AND CHAR_LENGTH(trade_id) <= 64 AND (symbol = '' OR symbol = 'BTCUSDT') AND occurred_at <= captured_at),
    CONSTRAINT fk_binance_usdm_income_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_order_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    provider_order_id BIGINT NOT NULL,
    client_order_id VARCHAR(36) COLLATE ascii_bin NOT NULL,
    symbol VARCHAR(16) COLLATE ascii_bin NOT NULL,
    status VARCHAR(32) COLLATE ascii_bin NOT NULL,
    side VARCHAR(4) COLLATE ascii_bin NOT NULL,
    order_type VARCHAR(32) COLLATE ascii_bin NOT NULL,
    executed_quantity NUMERIC(38, 18) NOT NULL,
    original_quantity NUMERIC(38, 18) NOT NULL,
    reduce_only BOOL NOT NULL,
    close_position BOOL NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_order_identity UNIQUE (run_id, provider_order_id),
    CONSTRAINT uq_binance_usdm_order_client_identity UNIQUE (run_id, client_order_id),
    CONSTRAINT ck_binance_usdm_order_values CHECK (symbol = 'BTCUSDT' AND side IN ('BUY', 'SELL') AND original_quantity > 0 AND executed_quantity >= 0 AND executed_quantity <= original_quantity),
    CONSTRAINT fk_binance_usdm_order_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_position_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    symbol VARCHAR(16) COLLATE ascii_bin NOT NULL,
    position_side VARCHAR(8) COLLATE ascii_bin NOT NULL,
    amount NUMERIC(38, 18) NOT NULL,
    entry_price NUMERIC(38, 18) NOT NULL,
    mark_price NUMERIC(38, 18) NOT NULL,
    unrealized_pnl NUMERIC(38, 18) NOT NULL,
    isolated_margin NUMERIC(38, 18) NOT NULL,
    notional NUMERIC(38, 18) NOT NULL,
    margin_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    initial_margin NUMERIC(38, 18) NOT NULL,
    maintenance_margin NUMERIC(38, 18) NOT NULL,
    position_initial_margin NUMERIC(38, 18) NOT NULL,
    open_order_initial_margin NUMERIC(38, 18) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_position_identity UNIQUE (run_id, symbol, position_side),
    CONSTRAINT ck_binance_usdm_position_values CHECK (symbol = 'BTCUSDT' AND position_side = 'BOTH' AND margin_asset = 'USDT' AND entry_price >= 0 AND mark_price >= 0 AND isolated_margin >= 0 AND initial_margin >= 0 AND maintenance_margin >= 0 AND position_initial_margin >= 0 AND open_order_initial_margin >= 0 AND updated_at <= captured_at),
    CONSTRAINT fk_binance_usdm_position_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE binance_usdm_trade_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    provider_trade_id BIGINT NOT NULL,
    provider_order_id BIGINT NOT NULL,
    symbol VARCHAR(16) COLLATE ascii_bin NOT NULL,
    side VARCHAR(4) COLLATE ascii_bin NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    price NUMERIC(38, 18) NOT NULL,
    commission NUMERIC(38, 18) NOT NULL,
    commission_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    realized_pnl NUMERIC(38, 18) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_binance_usdm_trade_identity UNIQUE (run_id, provider_trade_id),
    CONSTRAINT ck_binance_usdm_trade_values CHECK (symbol = 'BTCUSDT' AND side IN ('BUY', 'SELL') AND quantity > 0 AND price > 0 AND commission >= 0 AND commission_asset = 'USDT' AND occurred_at <= captured_at),
    CONSTRAINT fk_binance_usdm_trade_fact_run FOREIGN KEY(run_id) REFERENCES binance_usdm_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE exec_execution_checkpoint_scope (
    id BINARY(16) NOT NULL,
    watermark_id BINARY(16) NOT NULL,
    scope_kind VARCHAR(32) NOT NULL,
    scope_value VARCHAR(128) COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_checkpoint_scope_watermark FOREIGN KEY(watermark_id) REFERENCES exec_broker_execution_watermark (id) ON DELETE RESTRICT,
    CONSTRAINT uq_exec_checkpoint_scope UNIQUE (watermark_id, scope_kind, scope_value)
)""",
    """CREATE TABLE exec_execution_gap (
    id BINARY(16) NOT NULL,
    watermark_id BINARY(16) NOT NULL,
    from_sequence BIGINT NOT NULL,
    through_sequence BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_execution_gap_watermark FOREIGN KEY(watermark_id) REFERENCES exec_broker_execution_watermark (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_execution_gap_range CHECK ((from_sequence > 0) and (through_sequence >= from_sequence)),
    CONSTRAINT uq_exec_execution_gap_range UNIQUE (watermark_id, from_sequence, through_sequence)
)""",
    """CREATE TABLE exec_fill_charge_component (
    id BINARY(16) NOT NULL,
    fill_id BINARY(16) NOT NULL,
    component_ordinal INTEGER NOT NULL,
    amount NUMERIC(38, 18) NOT NULL,
    currency VARCHAR(3),
    settlement_asset VARCHAR(16),
    charge_kind VARCHAR(64) NOT NULL,
    effect VARCHAR(8) NOT NULL,
    leg_role VARCHAR(16) NOT NULL,
    charge_basis VARCHAR(24) NOT NULL,
    basis_quantity NUMERIC(38, 18),
    basis_notional NUMERIC(38, 18),
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_fill_charge_fill FOREIGN KEY(fill_id) REFERENCES exec_fill (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_fill_charge_basis CHECK (((charge_basis = 'PER_UNIT') and (basis_quantity > 0) and (basis_notional is null)) or ((charge_basis = 'PER_NOTIONAL') and (basis_notional > 0) and (basis_quantity is null)) or ((charge_basis = 'PER_ORDER_MINIMUM') and (basis_quantity is null) and (basis_notional is null))),
    CONSTRAINT ck_exec_fill_charge_currency CHECK (regexp_like(currency,'^[A-Z]{3}$')),
    CONSTRAINT ck_exec_fill_charge_positive_amount CHECK (amount > 0),
    CONSTRAINT uq_exec_fill_charge_component_ordinal UNIQUE (fill_id, component_ordinal),
    CONSTRAINT ck_exec_fill_charge_component_denomination CHECK ((currency IS NOT NULL AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset IS NOT NULL))
)""",
    """CREATE TABLE exec_position_lifecycle (
    id BINARY(16) NOT NULL,
    position_id BINARY(16) NOT NULL,
    lifecycle_ordinal INTEGER NOT NULL,
    opening_fill_id BINARY(16) NOT NULL,
    closing_fill_id BINARY(16),
    opened_at DATETIME NOT NULL,
    closed_at DATETIME,
    kind VARCHAR(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_position_lifecycle_close_fill FOREIGN KEY(closing_fill_id) REFERENCES exec_fill (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_position_lifecycle_open_fill FOREIGN KEY(opening_fill_id) REFERENCES exec_fill (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_position_lifecycle_position FOREIGN KEY(position_id) REFERENCES exec_position (id) ON DELETE RESTRICT,
    CONSTRAINT uq_exec_position_lifecycle_ordinal UNIQUE (position_id, lifecycle_ordinal)
)""",
    """CREATE TABLE exec_position_lot (
    id BINARY(16) NOT NULL,
    position_id BINARY(16) NOT NULL,
    opening_fill_id BINARY(16) NOT NULL,
    opened_quantity NUMERIC(38, 18) NOT NULL,
    remaining_quantity NUMERIC(38, 18) NOT NULL,
    opened_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exec_position_lot_opening_fill FOREIGN KEY(opening_fill_id) REFERENCES exec_fill (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exec_position_lot_position FOREIGN KEY(position_id) REFERENCES exec_position (id) ON DELETE RESTRICT,
    CONSTRAINT ck_exec_position_lot_quantities CHECK ((opened_quantity > 0) and (remaining_quantity >= 0)),
    CONSTRAINT uq_exec_position_lot_opening_fill UNIQUE (opening_fill_id)
)""",
    """CREATE TABLE risk_david_v6_session_anchor (
    id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    policy_version_id BINARY(16) NOT NULL,
    account_snapshot_id BINARY(16) NOT NULL,
    risk_snapshot_id BINARY(16) NOT NULL,
    market VARCHAR(16) COLLATE ascii_bin NOT NULL,
    session_key VARCHAR(32) COLLATE ascii_bin NOT NULL,
    session_started_at DATETIME NOT NULL,
    captured_at DATETIME NOT NULL,
    starting_equity NUMERIC(38, 18) NOT NULL,
    currency VARCHAR(3),
    settlement_asset VARCHAR(16),
    evidence_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_risk_david_v6_anchor_account FOREIGN KEY(account_id) REFERENCES exec_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_risk_david_v6_anchor_policy FOREIGN KEY(policy_version_id) REFERENCES risk_policy_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_risk_david_v6_anchor_snapshot FOREIGN KEY(account_snapshot_id) REFERENCES exec_account_snapshot (id) ON DELETE RESTRICT,
    CONSTRAINT fk_risk_david_v6_anchor_risk_snapshot FOREIGN KEY(risk_snapshot_id) REFERENCES risk_snapshot (id) ON DELETE RESTRICT,
    CONSTRAINT uq_risk_david_v6_anchor_session UNIQUE (account_id, market, session_key),
    CONSTRAINT ck_risk_david_v6_anchor_scope CHECK (market IN ('KRX_CASH', 'US_CASH', 'BINANCE_USDM') AND CHAR_LENGTH(session_key) > 0),
    CONSTRAINT ck_risk_david_v6_anchor_values CHECK (starting_equity > 0 AND captured_at >= session_started_at AND OCTET_LENGTH(evidence_hash) = 32),
    CONSTRAINT ck_risk_david_v6_anchor_denomination CHECK ((currency IS NOT NULL AND settlement_asset IS NULL) OR (currency IS NULL AND settlement_asset IS NOT NULL))
)""",
    """CREATE TABLE strategy_signal (
    id BINARY(16) NOT NULL,
    strategy_version_id BINARY(16) NOT NULL,
    setup_id BINARY(16) NOT NULL,
    feature_snapshot_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    signal_type VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_style VARCHAR(16) NOT NULL,
    planned_entry_price NUMERIC(38, 18) NOT NULL,
    trigger_price NUMERIC(38, 18) NOT NULL,
    invalidation_price NUMERIC(38, 18) NOT NULL,
    generated_at DATETIME NOT NULL,
    valid_until DATETIME NOT NULL,
    session_type VARCHAR(32) NOT NULL,
    signal_hash BINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_strategy_signal_feature_snapshot FOREIGN KEY(feature_snapshot_id) REFERENCES strategy_feature_snapshot (id),
    CONSTRAINT fk_strategy_signal_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id),
    CONSTRAINT fk_strategy_signal_setup FOREIGN KEY(setup_id) REFERENCES strategy_setup (id),
    CONSTRAINT fk_strategy_signal_version FOREIGN KEY(strategy_version_id) REFERENCES strategy_version (id),
    CONSTRAINT uq_strategy_signal_identity UNIQUE (setup_id, signal_type, signal_hash),
    CONSTRAINT ck_strategy_signal_validity CHECK (valid_until > generated_at),
    CONSTRAINT ck_strategy_signal_prices_positive CHECK (planned_entry_price > 0 AND trigger_price > 0 AND invalidation_price > 0)
)""",
    """CREATE TABLE toss_us_cash_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    settlement_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    state VARCHAR(16) COLLATE ascii_bin NOT NULL,
    available_cash NUMERIC(38, 18),
    settled_cash NUMERIC(38, 18),
    source_field VARCHAR(128) COLLATE ascii_bin,
    provider_as_of DATETIME NOT NULL,
    captured_at DATETIME NOT NULL,
    source_digest VARBINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_toss_us_cash_fact_identity UNIQUE (run_id, settlement_asset),
    CONSTRAINT ck_toss_us_cash_fact_state CHECK (state IN ('AVAILABLE', 'UNAVAILABLE', 'STALE', 'N/A', 'UNKNOWN') AND settlement_asset = 'USD'),
    CONSTRAINT ck_toss_us_cash_fact_shape CHECK (provider_as_of <= captured_at AND OCTET_LENGTH(source_digest) = 32 AND ((state = 'AVAILABLE' AND available_cash >= 0 AND (settled_cash IS NULL OR settled_cash >= 0) AND CHAR_LENGTH(source_field) BETWEEN 1 AND 128) OR (state <> 'AVAILABLE' AND available_cash IS NULL AND settled_cash IS NULL AND source_field IS NULL))),
    CONSTRAINT fk_toss_us_cash_fact_run FOREIGN KEY(run_id) REFERENCES toss_us_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE toss_us_order_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    provider_order_id VARCHAR(128) COLLATE ascii_bin NOT NULL,
    symbol VARCHAR(32) COLLATE ascii_bin NOT NULL,
    side VARCHAR(4) COLLATE ascii_bin NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    cumulative_fill_quantity NUMERIC(38, 18) NOT NULL,
    state VARCHAR(32) COLLATE ascii_bin NOT NULL,
    limit_price NUMERIC(38, 18),
    commission NUMERIC(38, 18),
    tax NUMERIC(38, 18),
    settlement_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    ordered_at DATETIME NOT NULL,
    filled_at DATETIME,
    canceled_at DATETIME,
    provider_as_of DATETIME NOT NULL,
    captured_at DATETIME NOT NULL,
    source_digest VARBINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_toss_us_order_fact_identity UNIQUE (run_id, provider_order_id),
    CONSTRAINT ck_toss_us_order_fact_scope CHECK (side IN ('BUY', 'SELL') AND state IN ('PENDING', 'PENDING_CANCEL', 'PENDING_REPLACE', 'PARTIAL_FILLED', 'FILLED', 'CANCELED', 'REJECTED', 'CANCEL_REJECTED', 'REPLACE_REJECTED', 'REPLACED') AND settlement_asset = 'USD' AND CHAR_LENGTH(provider_order_id) BETWEEN 1 AND 128 AND CHAR_LENGTH(symbol) BETWEEN 1 AND 32),
    CONSTRAINT ck_toss_us_order_fact_values CHECK (quantity > 0 AND cumulative_fill_quantity >= 0 AND cumulative_fill_quantity <= quantity AND (limit_price IS NULL OR limit_price > 0) AND (commission IS NULL OR commission >= 0) AND (tax IS NULL OR tax >= 0)),
    CONSTRAINT ck_toss_us_order_fact_provenance CHECK (ordered_at <= provider_as_of AND provider_as_of <= captured_at AND (filled_at IS NULL OR filled_at >= ordered_at) AND (canceled_at IS NULL OR canceled_at >= ordered_at) AND OCTET_LENGTH(source_digest) = 32),
    CONSTRAINT fk_toss_us_order_fact_run FOREIGN KEY(run_id) REFERENCES toss_us_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE toss_us_position_fact (
    id BINARY(16) NOT NULL,
    run_id BINARY(16) NOT NULL,
    symbol VARCHAR(32) COLLATE ascii_bin NOT NULL,
    settlement_asset VARCHAR(8) COLLATE ascii_bin NOT NULL,
    total_quantity NUMERIC(38, 18) NOT NULL,
    sellable_quantity NUMERIC(38, 18) NOT NULL,
    average_price NUMERIC(38, 18) NOT NULL,
    market_value NUMERIC(38, 18) NOT NULL,
    provider_as_of DATETIME NOT NULL,
    captured_at DATETIME NOT NULL,
    source_digest VARBINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_toss_us_position_fact_identity UNIQUE (run_id, symbol),
    CONSTRAINT ck_toss_us_position_fact_values CHECK (settlement_asset = 'USD' AND CHAR_LENGTH(symbol) BETWEEN 1 AND 32 AND total_quantity >= 0 AND sellable_quantity >= 0 AND sellable_quantity <= total_quantity AND average_price >= 0 AND market_value >= 0),
    CONSTRAINT ck_toss_us_position_fact_provenance CHECK (provider_as_of <= captured_at AND OCTET_LENGTH(source_digest) = 32),
    CONSTRAINT fk_toss_us_position_fact_run FOREIGN KEY(run_id) REFERENCES toss_us_reconciliation_run (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE strategy_david_v6_decision (
    id BINARY(16) NOT NULL,
    manifest_id BINARY(16) NOT NULL,
    strategy_signal_id BINARY(16),
    strategy_version_id BINARY(16) NOT NULL,
    setup_id BINARY(16) NOT NULL,
    feature_snapshot_id BINARY(16) NOT NULL,
    instrument_id BINARY(16) NOT NULL,
    market VARCHAR(16) COLLATE ascii_bin NOT NULL,
    family VARCHAR(16) COLLATE ascii_bin NOT NULL,
    grade VARCHAR(16) COLLATE ascii_bin NOT NULL,
    side VARCHAR(8) COLLATE ascii_bin NOT NULL,
    order_style VARCHAR(16) COLLATE ascii_bin NOT NULL,
    matched_indicator_count BIGINT NOT NULL,
    blocker_count BIGINT NOT NULL,
    planned_entry NUMERIC(38, 18),
    structural_stop NUMERIC(38, 18),
    target_price NUMERIC(38, 18),
    risk_fraction NUMERIC(18, 8) NOT NULL,
    calculated_quantity NUMERIC(38, 18) NOT NULL,
    expected_cost NUMERIC(38, 18),
    source_evidence_hashes JSON NOT NULL,
    source_evidence_manifest_hash VARBINARY(32) NOT NULL,
    completed_evidence_at DATETIME NOT NULL,
    generated_at DATETIME NOT NULL,
    valid_until DATETIME NOT NULL,
    decision_hash VARBINARY(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_strategy_david_v6_decision_identity UNIQUE (setup_id, instrument_id, decision_hash),
    CONSTRAINT uq_strategy_david_v6_decision_signal UNIQUE (strategy_signal_id),
    CONSTRAINT ck_strategy_david_v6_decision_scope CHECK (market IN ('KRX_CASH', 'US_CASH', 'BINANCE_USDM') AND family IN ('METODO', 'HLIT') AND grade IN ('REJECT', 'NORMAL', 'A_CANDIDATE', 'A') AND side IN ('BUY', 'SELL') AND order_style IN ('MARKET', 'LIMIT') AND (family = 'HLIT' OR market IN ('KRX_CASH', 'US_CASH'))),
    CONSTRAINT ck_strategy_david_v6_decision_times CHECK (completed_evidence_at <= generated_at AND generated_at < valid_until),
    CONSTRAINT ck_strategy_david_v6_decision_values CHECK (matched_indicator_count >= 0 AND blocker_count >= 0 AND risk_fraction BETWEEN 0 AND 0.0075 AND calculated_quantity >= 0),
    CONSTRAINT ck_strategy_david_v6_decision_shape CHECK ((grade = 'REJECT' AND blocker_count > 0 AND strategy_signal_id IS NULL AND planned_entry IS NULL AND structural_stop IS NULL AND target_price IS NULL AND expected_cost IS NULL AND risk_fraction = 0 AND calculated_quantity = 0) OR (grade <> 'REJECT' AND blocker_count = 0 AND strategy_signal_id IS NOT NULL AND planned_entry > 0 AND structural_stop > 0 AND target_price > 0 AND expected_cost >= 0 AND risk_fraction > 0 AND calculated_quantity > 0 AND ((side = 'BUY' AND structural_stop < planned_entry AND planned_entry < target_price) OR (side = 'SELL' AND target_price < planned_entry AND planned_entry < structural_stop)))),
    CONSTRAINT ck_strategy_david_v6_decision_hashes CHECK (OCTET_LENGTH(source_evidence_manifest_hash) = 32 AND OCTET_LENGTH(decision_hash) = 32),
    CONSTRAINT fk_strategy_david_v6_decision_manifest FOREIGN KEY(manifest_id, strategy_version_id) REFERENCES strategy_david_v6_manifest (id, strategy_version_id) ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_david_v6_decision_version FOREIGN KEY(strategy_version_id) REFERENCES strategy_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_david_v6_decision_setup FOREIGN KEY(setup_id) REFERENCES strategy_setup (id) ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_david_v6_decision_feature_snapshot FOREIGN KEY(feature_snapshot_id) REFERENCES strategy_feature_snapshot (id) ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_david_v6_decision_instrument FOREIGN KEY(instrument_id) REFERENCES core_instrument (id) ON DELETE RESTRICT,
    CONSTRAINT fk_strategy_david_v6_decision_signal FOREIGN KEY(strategy_signal_id) REFERENCES strategy_signal (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE strategy_david_v6_blocker (
    decision_id BINARY(16) NOT NULL,
    ordinal BIGINT NOT NULL,
    blocker_code VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    CONSTRAINT pk_strategy_david_v6_blocker PRIMARY KEY (decision_id, blocker_code),
    CONSTRAINT uq_strategy_david_v6_blocker_ordinal UNIQUE (decision_id, ordinal),
    CONSTRAINT ck_strategy_david_v6_blocker_scope CHECK (ordinal >= 0 AND CHAR_LENGTH(blocker_code) BETWEEN 1 AND 128 AND blocker_code = TRIM(blocker_code)),
    CONSTRAINT fk_strategy_david_v6_blocker_decision FOREIGN KEY(decision_id) REFERENCES strategy_david_v6_decision (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE strategy_david_v6_indicator (
    decision_id BINARY(16) NOT NULL,
    ordinal BIGINT NOT NULL,
    indicator_key VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
    mandatory BOOL NOT NULL,
    evidence_state VARCHAR(16) COLLATE ascii_bin NOT NULL,
    evidence_hash VARBINARY(32) NOT NULL,
    CONSTRAINT pk_strategy_david_v6_indicator PRIMARY KEY (decision_id, indicator_key),
    CONSTRAINT uq_strategy_david_v6_indicator_ordinal UNIQUE (decision_id, ordinal),
    CONSTRAINT ck_strategy_david_v6_indicator_scope CHECK (ordinal >= 0 AND CHAR_LENGTH(indicator_key) BETWEEN 1 AND 128 AND indicator_key = TRIM(indicator_key) AND evidence_state = 'AVAILABLE'),
    CONSTRAINT ck_strategy_david_v6_indicator_hash CHECK (OCTET_LENGTH(evidence_hash) = 32),
    CONSTRAINT fk_strategy_david_v6_indicator_decision FOREIGN KEY(decision_id) REFERENCES strategy_david_v6_decision (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX ix_backoffice_command_actor_started ON backoffice_command (actor_email, started_at)""",
    """CREATE INDEX ix_backoffice_command_target_started ON backoffice_command (target_type, target_key, started_at)""",
    """CREATE INDEX ix_backoffice_secret_version_history ON backoffice_secret_version (logical_name, created_at)""",
    """CREATE INDEX ix_ops_audit_log_scope_occurred_at ON ops_audit_log (scope_type, scope_key, occurred_at)""",
    """CREATE INDEX ix_ops_incident_scope ON ops_incident (scope_type, scope_key)""",
    """CREATE INDEX ix_ops_incident_severity_status ON ops_incident (severity, status)""",
    """CREATE INDEX ix_ops_outbox_claimable ON ops_outbox_event (published_at, next_attempt_at, claim_expires_at, created_at)""",
    """CREATE INDEX ix_backoffice_secret_activation_history ON backoffice_secret_activation (logical_name, activated_at)""",
    """CREATE INDEX ix_core_exchange_market_id ON core_exchange (market_id)""",
    """CREATE INDEX ix_core_instrument_exchange_id ON core_instrument (exchange_id)""",
    """CREATE INDEX ix_binance_usdm_reconciliation_readiness ON binance_usdm_reconciliation_run (binding_id, result, completed_at)""",
    """CREATE INDEX ix_toss_us_reconciliation_readiness ON toss_us_reconciliation_run (binding_id, result, completed_at)""",
    """CREATE INDEX ix_toss_us_recovery_expiry ON toss_us_recovery_lease (binding_id, terminal_state, lease_expires_at)""",
    """CREATE INDEX ix_binance_usdm_algo_provider_identity ON binance_usdm_algo_order_fact (provider_algo_id, captured_at)""",
    """CREATE INDEX ix_binance_usdm_income_provider_identity ON binance_usdm_income_fact (provider_transaction_id, occurred_at)""",
    """CREATE INDEX ix_binance_usdm_order_provider_identity ON binance_usdm_order_fact (provider_order_id, captured_at)""",
    """CREATE INDEX ix_binance_usdm_position_symbol ON binance_usdm_position_fact (symbol, captured_at)""",
    """CREATE INDEX ix_binance_usdm_trade_provider_identity ON binance_usdm_trade_fact (provider_trade_id, occurred_at)""",
    """CREATE INDEX ix_toss_us_order_provider_identity ON toss_us_order_fact (provider_order_id, ordered_at)""",
    """CREATE INDEX ix_toss_us_position_symbol ON toss_us_position_fact (symbol, provider_as_of)""",
)


def upgrade() -> None:
    # exec_order, exec_order_intent, exec_reconciliation_diff and risk_decision
    # reference each other, so no creation order resolves every foreign key.
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    try:
        for statement in _CREATE:
            op.execute(statement)
    finally:
        op.execute("SET FOREIGN_KEY_CHECKS = 1")


def downgrade() -> None:
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    for name in reversed(TABLES):
        op.execute(f"DROP TABLE IF EXISTS `{name}`")
    op.execute("SET FOREIGN_KEY_CHECKS = 1")
